server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://mongo:password@localhost:27017/order-service?authSource=admin}

logging:
  level:
    org:
      apache:
        kafka: OFF